/*
 * Buyt.java
 *
 * Created on __DATE__, __TIME__
 */

package UserView;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import model.Film;
import model.Sessions;
import model.User;

/**
 *
 * @author  __USER__
 */
public class Buyt extends javax.swing.JFrame {
	/** Creates new form Buyt */
	public Buyt() {
		initComponents();
		this.setLocationRelativeTo(null);
		this.jTextField3.setText(User.getUname());
		addlistenner();
		resetSomething();
		jList1.setSelectedIndex(0);
		if (jComboBox2.getSelectedIndex() >= 0) {
			jComboBox2.setSelectedIndex(0);
		}
		try {
			money = new User().checkUSER(jTextField3);
			jTextField4.setText("" + money);
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel2 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox();
		jSeparator1 = new javax.swing.JSeparator();
		jButton65 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton66 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jButton14 = new javax.swing.JButton();
		jButton15 = new javax.swing.JButton();
		jButton16 = new javax.swing.JButton();
		jButton17 = new javax.swing.JButton();
		jButton18 = new javax.swing.JButton();
		jButton19 = new javax.swing.JButton();
		jButton20 = new javax.swing.JButton();
		jButton21 = new javax.swing.JButton();
		jButton22 = new javax.swing.JButton();
		jButton23 = new javax.swing.JButton();
		jButton24 = new javax.swing.JButton();
		jButton25 = new javax.swing.JButton();
		jButton26 = new javax.swing.JButton();
		jButton27 = new javax.swing.JButton();
		jButton28 = new javax.swing.JButton();
		jButton29 = new javax.swing.JButton();
		jButton30 = new javax.swing.JButton();
		jButton31 = new javax.swing.JButton();
		jButton32 = new javax.swing.JButton();
		jButton33 = new javax.swing.JButton();
		jButton34 = new javax.swing.JButton();
		jButton35 = new javax.swing.JButton();
		jButton36 = new javax.swing.JButton();
		jButton37 = new javax.swing.JButton();
		jButton38 = new javax.swing.JButton();
		jButton39 = new javax.swing.JButton();
		jButton40 = new javax.swing.JButton();
		jButton41 = new javax.swing.JButton();
		jButton42 = new javax.swing.JButton();
		jButton43 = new javax.swing.JButton();
		jButton44 = new javax.swing.JButton();
		jButton45 = new javax.swing.JButton();
		jButton46 = new javax.swing.JButton();
		jButton47 = new javax.swing.JButton();
		jButton48 = new javax.swing.JButton();
		jButton49 = new javax.swing.JButton();
		jButton50 = new javax.swing.JButton();
		jButton51 = new javax.swing.JButton();
		jButton52 = new javax.swing.JButton();
		jButton53 = new javax.swing.JButton();
		jButton54 = new javax.swing.JButton();
		jButton55 = new javax.swing.JButton();
		jButton56 = new javax.swing.JButton();
		jButton57 = new javax.swing.JButton();
		jButton58 = new javax.swing.JButton();
		jButton59 = new javax.swing.JButton();
		jButton60 = new javax.swing.JButton();
		jButton61 = new javax.swing.JButton();
		jButton62 = new javax.swing.JButton();
		jButton63 = new javax.swing.JButton();
		jButton64 = new javax.swing.JButton();
		jButton67 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		jLabel1.setText("\u5927\u5385\uff1a");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "1" }));

		jLabel2.setText("\u653e\u6620\u65f6\u95f4\uff1a");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "1" }));

		jButton65.setText("\u8d2d\u4e70");
		jButton65.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton65ActionPerformed(evt);
			}
		});

		jTextField1.setEditable(false);

		jLabel3.setText("\u7535\u5f71\u540d\uff1a");

		jLabel4.setText("\u4ef7\u683c\uff1a");

		jTextField2.setEditable(false);

		jButton66.setText("\u8fd4\u56de");
		jButton66.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton66ActionPerformed(evt);
			}
		});

		jLabel5.setText("\u7528\u6237\u540d\uff1a");

		jTextField3.setEditable(false);

		jLabel6.setText("\u4f59\u989d\uff1a");

		jTextField4.setEditable(false);

		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "1" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(jList1);

		jButton1.setBackground(new java.awt.Color(255, 255, 255));
		jButton1.setText("01");

		jButton2.setBackground(new java.awt.Color(255, 255, 255));
		jButton2.setText("02");

		jButton3.setBackground(new java.awt.Color(255, 255, 255));
		jButton3.setText("03");

		jButton4.setBackground(new java.awt.Color(255, 255, 255));
		jButton4.setText("04");

		jButton5.setBackground(new java.awt.Color(255, 255, 255));
		jButton5.setText("05");

		jButton6.setBackground(new java.awt.Color(255, 255, 255));
		jButton6.setText("06");

		jButton7.setBackground(new java.awt.Color(255, 255, 255));
		jButton7.setText("07");

		jButton8.setBackground(new java.awt.Color(255, 255, 255));
		jButton8.setText("08");

		jButton9.setBackground(new java.awt.Color(255, 255, 255));
		jButton9.setText("01");

		jButton10.setBackground(new java.awt.Color(255, 255, 255));
		jButton10.setText("02");

		jButton11.setBackground(new java.awt.Color(255, 255, 255));
		jButton11.setText("03");

		jButton12.setBackground(new java.awt.Color(255, 255, 255));
		jButton12.setText("04");

		jButton13.setBackground(new java.awt.Color(255, 255, 255));
		jButton13.setText("05");

		jButton14.setBackground(new java.awt.Color(255, 255, 255));
		jButton14.setText("06");

		jButton15.setBackground(new java.awt.Color(255, 255, 255));
		jButton15.setText("07");

		jButton16.setBackground(new java.awt.Color(255, 255, 255));
		jButton16.setText("08");

		jButton17.setBackground(new java.awt.Color(255, 255, 255));
		jButton17.setText("01");

		jButton18.setBackground(new java.awt.Color(255, 255, 255));
		jButton18.setText("02");

		jButton19.setBackground(new java.awt.Color(255, 255, 255));
		jButton19.setText("03");

		jButton20.setBackground(new java.awt.Color(255, 255, 255));
		jButton20.setText("04");

		jButton21.setBackground(new java.awt.Color(255, 255, 255));
		jButton21.setText("05");

		jButton22.setBackground(new java.awt.Color(255, 255, 255));
		jButton22.setText("06");

		jButton23.setBackground(new java.awt.Color(255, 255, 255));
		jButton23.setText("07");

		jButton24.setBackground(new java.awt.Color(255, 255, 255));
		jButton24.setText("08");

		jButton25.setBackground(new java.awt.Color(255, 255, 255));
		jButton25.setText("01");

		jButton26.setBackground(new java.awt.Color(255, 255, 255));
		jButton26.setText("02");

		jButton27.setBackground(new java.awt.Color(255, 255, 255));
		jButton27.setText("03");

		jButton28.setBackground(new java.awt.Color(255, 255, 255));
		jButton28.setText("04");

		jButton29.setBackground(new java.awt.Color(255, 255, 255));
		jButton29.setText("05");

		jButton30.setBackground(new java.awt.Color(255, 255, 255));
		jButton30.setText("06");

		jButton31.setBackground(new java.awt.Color(255, 255, 255));
		jButton31.setText("07");

		jButton32.setBackground(new java.awt.Color(255, 255, 255));
		jButton32.setText("08");

		jButton33.setBackground(new java.awt.Color(255, 255, 255));
		jButton33.setText("01");

		jButton34.setBackground(new java.awt.Color(255, 255, 255));
		jButton34.setText("02");

		jButton35.setBackground(new java.awt.Color(255, 255, 255));
		jButton35.setText("03");

		jButton36.setBackground(new java.awt.Color(255, 255, 255));
		jButton36.setText("04");

		jButton37.setBackground(new java.awt.Color(255, 255, 255));
		jButton37.setText("05");

		jButton38.setBackground(new java.awt.Color(255, 255, 255));
		jButton38.setText("06");

		jButton39.setBackground(new java.awt.Color(255, 255, 255));
		jButton39.setText("07");

		jButton40.setBackground(new java.awt.Color(255, 255, 255));
		jButton40.setText("08");

		jButton41.setBackground(new java.awt.Color(255, 255, 255));
		jButton41.setText("01");

		jButton42.setBackground(new java.awt.Color(255, 255, 255));
		jButton42.setText("02");

		jButton43.setBackground(new java.awt.Color(255, 255, 255));
		jButton43.setText("03");

		jButton44.setBackground(new java.awt.Color(255, 255, 255));
		jButton44.setText("04");

		jButton45.setBackground(new java.awt.Color(255, 255, 255));
		jButton45.setText("05");

		jButton46.setBackground(new java.awt.Color(255, 255, 255));
		jButton46.setText("06");

		jButton47.setBackground(new java.awt.Color(255, 255, 255));
		jButton47.setText("07");

		jButton48.setBackground(new java.awt.Color(255, 255, 255));
		jButton48.setText("08");

		jButton49.setBackground(new java.awt.Color(255, 255, 255));
		jButton49.setText("01");

		jButton50.setBackground(new java.awt.Color(255, 255, 255));
		jButton50.setText("02");

		jButton51.setBackground(new java.awt.Color(255, 255, 255));
		jButton51.setText("03");

		jButton52.setBackground(new java.awt.Color(255, 255, 255));
		jButton52.setText("04");

		jButton53.setBackground(new java.awt.Color(255, 255, 255));
		jButton53.setText("05");

		jButton54.setBackground(new java.awt.Color(255, 255, 255));
		jButton54.setText("06");

		jButton55.setBackground(new java.awt.Color(255, 255, 255));
		jButton55.setText("07");

		jButton56.setBackground(new java.awt.Color(255, 255, 255));
		jButton56.setText("08");

		jButton57.setBackground(new java.awt.Color(255, 255, 255));
		jButton57.setText("01");

		jButton58.setBackground(new java.awt.Color(255, 255, 255));
		jButton58.setText("02");

		jButton59.setBackground(new java.awt.Color(255, 255, 255));
		jButton59.setText("03");

		jButton60.setBackground(new java.awt.Color(255, 255, 255));
		jButton60.setText("04");

		jButton61.setBackground(new java.awt.Color(255, 255, 255));
		jButton61.setText("05");

		jButton62.setBackground(new java.awt.Color(255, 255, 255));
		jButton62.setText("06");

		jButton63.setBackground(new java.awt.Color(255, 255, 255));
		jButton63.setText("07");

		jButton64.setBackground(new java.awt.Color(255, 255, 255));
		jButton64.setText("08");

		jButton67.setText("\u9000\u51fa");
		jButton67.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton67ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												61,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jTextField1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												130,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel5,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												61,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												17,
																												17,
																												17)
																										.addComponent(
																												jTextField3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												130,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel2)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jComboBox2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												177,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(
																				71,
																				71,
																				71)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								61,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								61,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								61,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				45,
																				45,
																				45)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextField4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								130,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								130,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jComboBox1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								177,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				1175,
																				1175,
																				1175))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jSeparator1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								709,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jScrollPane1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												90,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												31,
																												31,
																												31)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jButton1,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton2,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton3,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton4,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton5,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton6,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton7,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton8,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jButton9,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton10,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton11,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton12,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton13,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton14,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton15,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton16,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jButton17,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton18,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton19,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton20,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton21,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton22,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton23,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton24,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jButton25,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton26,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton27,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton28,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton29,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton30,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton31,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton32,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jButton33,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton34,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton35,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton36,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton37,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton38,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton39,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton40,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jButton41,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton42,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton43,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton44,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton45,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton46,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton47,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton48,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jButton49,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton50,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton51,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton52,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton53,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton54,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton55,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jButton56,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				63,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				jPanel1Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING,
																																								jPanel1Layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jButton57,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												63,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												jButton58,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												63,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																																						.addGroup(
																																								jPanel1Layout
																																										.createSequentialGroup()
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												jButton67,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												94,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addGap(
																																												50,
																																												50,
																																												50)))
																																		.addGroup(
																																				jPanel1Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																						.addGroup(
																																								jPanel1Layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jButton59,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												63,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												jButton60,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												63,
																																												javax.swing.GroupLayout.PREFERRED_SIZE))
																																						.addComponent(
																																								jButton66,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								90,
																																								javax.swing.GroupLayout.PREFERRED_SIZE))
																																		.addGroup(
																																				jPanel1Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addGroup(
																																								jPanel1Layout
																																										.createSequentialGroup()
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												jButton61,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												63,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												jButton62,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												63,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												jButton63,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												63,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												jButton64,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												63,
																																												javax.swing.GroupLayout.PREFERRED_SIZE))
																																						.addGroup(
																																								jPanel1Layout
																																										.createSequentialGroup()
																																										.addGap(
																																												93,
																																												93,
																																												93)
																																										.addComponent(
																																												jButton65,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												82,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)))))))
																		.addGap(
																				1137,
																				1137,
																				1137)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel6))
																		.addGap(
																				34,
																				34,
																				34)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jTextField2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel5)
																						.addComponent(
																								jTextField3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												85,
																												85,
																												85)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																jLabel2,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																40,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																jComboBox2,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																33,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																jLabel1,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																40,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																jComboBox1,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																33,
																																javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												26,
																												26,
																												26)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																jLabel3)
																														.addComponent(
																																jTextField1,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.PREFERRED_SIZE))))))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												13,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				41,
																				41,
																				41)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton7,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton8,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton9,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton10,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton11,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton12,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton13,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton14,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton15,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton16,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton17,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton18,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton19,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton20,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton21,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton22,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton23,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton24,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton25,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton26,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton27,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton28,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton29,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton30,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton31,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton32,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton33,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton34,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton35,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton36,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton37,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton38,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton39,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton40,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton41,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton42,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton43,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton44,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton45,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton46,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton47,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton48,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton49,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton50,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton51,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton52,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton53,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton54,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton55,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton56,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton57,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton58,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton59,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton60,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton61,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton62,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton63,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton64,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								39,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				43,
																				43,
																				43)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton67,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								86,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton66,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								86,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton65,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								86,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				45,
																				45,
																				45)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				372,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(32, 32, 32)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 761,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			money = new User().checkUSER(jTextField3);
			username = jTextField3.getText();
			if (money > Float.parseFloat(jTextField2.getText())) {
				money = new User().getTicket(pid, jComboBox1.getSelectedItem()
						.toString(), jTextField1.getText(), hot, jComboBox2
						.getSelectedItem().toString(), waitsize, Float
						.parseFloat(jTextField2.getText()), username, money);
				seat = new User().chooseSeat(seat.length, seat[0].length, pid);
				waitsize = new int[5][3];
				addlistenner();
				jTextField4.setText("" + money);
			} else {
				JOptionPane.showMessageDialog(null, "余额不足");
			}
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {
		new Buyticket().setVisible(true);
		setVisible(false);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Buyt().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton jButton18;
	private javax.swing.JButton jButton19;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton20;
	private javax.swing.JButton jButton21;
	private javax.swing.JButton jButton22;
	private javax.swing.JButton jButton23;
	private javax.swing.JButton jButton24;
	private javax.swing.JButton jButton25;
	private javax.swing.JButton jButton26;
	private javax.swing.JButton jButton27;
	private javax.swing.JButton jButton28;
	private javax.swing.JButton jButton29;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton30;
	private javax.swing.JButton jButton31;
	private javax.swing.JButton jButton32;
	private javax.swing.JButton jButton33;
	private javax.swing.JButton jButton34;
	private javax.swing.JButton jButton35;
	private javax.swing.JButton jButton36;
	private javax.swing.JButton jButton37;
	private javax.swing.JButton jButton38;
	private javax.swing.JButton jButton39;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton40;
	private javax.swing.JButton jButton41;
	private javax.swing.JButton jButton42;
	private javax.swing.JButton jButton43;
	private javax.swing.JButton jButton44;
	private javax.swing.JButton jButton45;
	private javax.swing.JButton jButton46;
	private javax.swing.JButton jButton47;
	private javax.swing.JButton jButton48;
	private javax.swing.JButton jButton49;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton50;
	private javax.swing.JButton jButton51;
	private javax.swing.JButton jButton52;
	private javax.swing.JButton jButton53;
	private javax.swing.JButton jButton54;
	private javax.swing.JButton jButton55;
	private javax.swing.JButton jButton56;
	private javax.swing.JButton jButton57;
	private javax.swing.JButton jButton58;
	private javax.swing.JButton jButton59;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton60;
	private javax.swing.JButton jButton61;
	private javax.swing.JButton jButton62;
	private javax.swing.JButton jButton63;
	private javax.swing.JButton jButton64;
	private javax.swing.JButton jButton65;
	private javax.swing.JButton jButton66;
	private javax.swing.JButton jButton67;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JList jList1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables
	private int[][] seat = new User().chooseSeat(7, 8, "");
	private int[][] waitsize = new int[5][3];
	private float money;
	private String pid = null;
	private int hot = -1;
	int bilibili = 0;
	String username = "";
	private List<Sessions> mlist = new User().managerHall();
	private List<Film> flist = new User().showFilm();

	private void resetSomething() {
		final String[] fnames = new String[flist.size()];
		for (int i = 0; i < flist.size(); i++) {
			fnames[i] = flist.get(i).getFname();
		}
		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = fnames;

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});

		jList1.addListSelectionListener(new ListSelectionListener() {

			@Override
			public void valueChanged(ListSelectionEvent e) {
				// TODO Auto-generated method stub
				int i = jList1.getSelectedIndex();
				if (jComboBox1.getItemCount() > 0) {
					jComboBox1.removeAllItems();
				}
				if (jComboBox2.getItemCount() > 0) {
					jComboBox2.removeAllItems();
				}
				for (int a = 0; a < mlist.size(); a++) {
					System.out.println(mlist.get(a).getHname() + ":"
							+ mlist.get(a).getPlayID() + ":"
							+ mlist.get(a).getPlaytime());
					if (flist.get(i).getFname().equals(mlist.get(a).getFname())) {
						jComboBox2.addItem(mlist.get(a).getStarttime());
					}
				}
				if (jComboBox1.getSelectedIndex() >= 0) {

					jComboBox1.setSelectedIndex(0);
				}
				jTextField1.setText(flist.get(i).getFname());
				jTextField2.setText(Float.toString(flist.get(i).getPrice()));
				hot = flist.get(i).getHot();
				if (jComboBox2.getItemCount() == 0) {
					JOptionPane.showMessageDialog(null, "该电影还未上映");
					waitsize = null;
					addlistenner();
				}

			}
		});

		jComboBox2.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub

				if (jComboBox2.getSelectedIndex() != -1) {
					jComboBox1.removeAllItems();
					for (int a = 0; a < mlist.size(); a++) {
						if (jComboBox2.getSelectedItem().equals(
								mlist.get(a).getStarttime())) {
							jComboBox1.addItem(mlist.get(a).getHname());
							//自动生成影厅
						}
					}
				}
				if (jComboBox1.getSelectedIndex() != -1
						|| jComboBox2.getSelectedIndex() != -1) {
					for (int i = 0; i < mlist.size(); i++) {
						if (jComboBox1.getSelectedItem().equals(
								mlist.get(i).getHname())
								&& (jComboBox2.getSelectedItem().equals(mlist
										.get(i).getStarttime()))) {
							System.out.println("选项栏自动生成座位");
							seat = new User().chooseSeat(mlist.get(i).getX(),
									mlist.get(i).getY(), mlist.get(i)
											.getPlayID());
							pid = mlist.get(i).getPlayID();
							waitsize = new int[5][3];
							addlistenner();
						}
					}
				}
			}

		});
		jComboBox1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				if (jComboBox1.getSelectedIndex() != -1) {
					for (int i = 0; i < mlist.size(); i++) {
						if (jComboBox1.getSelectedItem().equals(
								mlist.get(i).getHname())) {
							System.out.println(":" + mlist.get(i).getPlayID());
							System.out.println("选项栏自动生成座位");
							seat = new User().chooseSeat(mlist.get(i).getX(),
									mlist.get(i).getY(), mlist.get(i)
											.getPlayID());
							pid = mlist.get(i).getPlayID();
							waitsize = new int[5][3];
							addlistenner();
						}
					}
				} else {
					seat = new int[1][0];
					pid = "";
					waitsize = new int[5][3];
					addlistenner();
				}
			}
		});
	}

	public void addlisten(final JButton jb, final int x, final int y) {
		if (seat.length != 0) {
			int closize = seat.length;
			int rowsize = seat[0].length;
			jb.setEnabled(true);
			jb.setVisible(true);
			if (jb.getActionListeners().length != 0) {
				jb.removeActionListener(jb.getActionListeners()[0]);
			}
			jb.setBackground(Color.WHITE);
			if (x >= closize || y >= rowsize) {
				jb.setVisible(false);
			} else {
				if (seat[x][y] == 1) {
					System.out.println("aaa" + x + " " + y);
					jb.setEnabled(false);
					jb.setBackground(new Color(255, 204, 0));
				}
				jb.addActionListener(new ActionListener() {

					@Override
					public void actionPerformed(ActionEvent e) {
						// TODO Auto-generated method stub
						int a = bilibili++;
						if (jb.getBackground().equals(Color.WHITE)) {

							int i = 0;
							while (true) {
								System.out.println(a);
								if (i == 5) {
									System.out.println("你只能选择五个座位");
									JOptionPane.showMessageDialog(null,
											"你只能选择五个座位");
									break;
								}
								if (waitsize[i][0] == 0) {
									waitsize[i][0] = 1;
									waitsize[i][1] = x;
									waitsize[i][2] = y;
									System.out.println("选座成功,剩余" + (4 - i)
											+ "个位置");
									JOptionPane.showMessageDialog(null,
											"选座成功,剩余" + (4 - i) + "个位置");
									jb.setBackground(new Color(255, 204, 0));
									break;
								} else {
									i++;
								}

							}
						} else {
							if (jb.getBackground().equals(
									new Color(255, 204, 0))) {
								int i = 4;
								while (true) {
									if (i == -1) {
										JOptionPane.showMessageDialog(null,
												"还没有选择座位");
										break;
									}
									if (waitsize[i][0] == 1) {
										waitsize[i][0] = 0;
										waitsize[i][1] = 0;
										waitsize[i][2] = 0;
										JOptionPane.showMessageDialog(null,
												"取消选座成功");
										System.out.println("取消选座成功");
										jb.setBackground(Color.white);
										break;
									} else {
										i--;
									}
								}
							}
						}
					}
				});
			}
		}
	}

	public void addlistenner() {
		waitsize = new int[5][3];
		addlisten(jButton1, 0, 0);
		addlisten(jButton2, 0, 1);
		addlisten(jButton3, 0, 2);
		addlisten(jButton4, 0, 3);
		addlisten(jButton5, 0, 4);
		addlisten(jButton6, 0, 5);
		addlisten(jButton7, 0, 6);
		addlisten(jButton8, 0, 7);
		addlisten(jButton9, 1, 0);
		addlisten(jButton10, 1, 1);
		addlisten(jButton11, 1, 2);
		addlisten(jButton12, 1, 3);
		addlisten(jButton13, 1, 4);
		addlisten(jButton14, 1, 5);
		addlisten(jButton15, 1, 6);
		addlisten(jButton16, 1, 7);
		addlisten(jButton17, 2, 0);
		addlisten(jButton18, 2, 1);
		addlisten(jButton19, 2, 2);
		addlisten(jButton20, 2, 3);
		addlisten(jButton21, 2, 4);
		addlisten(jButton22, 2, 5);
		addlisten(jButton23, 2, 6);
		addlisten(jButton24, 2, 7);
		addlisten(jButton25, 3, 0);
		addlisten(jButton26, 3, 1);
		addlisten(jButton27, 3, 2);
		addlisten(jButton28, 3, 3);
		addlisten(jButton29, 3, 4);
		addlisten(jButton30, 3, 5);
		addlisten(jButton31, 3, 6);
		addlisten(jButton32, 3, 7);
		addlisten(jButton33, 4, 0);
		addlisten(jButton34, 4, 1);
		addlisten(jButton35, 4, 2);
		addlisten(jButton36, 4, 3);
		addlisten(jButton37, 4, 4);
		addlisten(jButton38, 4, 5);
		addlisten(jButton39, 4, 6);
		addlisten(jButton40, 4, 7);
		addlisten(jButton41, 5, 0);
		addlisten(jButton42, 5, 1);
		addlisten(jButton43, 5, 2);
		addlisten(jButton44, 4, 3);
		addlisten(jButton45, 5, 4);
		addlisten(jButton46, 5, 5);
		addlisten(jButton47, 5, 6);
		addlisten(jButton48, 5, 7);
		addlisten(jButton49, 6, 0);
		addlisten(jButton50, 6, 1);
		addlisten(jButton51, 6, 2);
		addlisten(jButton52, 6, 3);
		addlisten(jButton53, 6, 4);
		addlisten(jButton54, 6, 5);
		addlisten(jButton55, 6, 6);
		addlisten(jButton56, 6, 7);
		addlisten(jButton57, 7, 0);
		addlisten(jButton58, 7, 1);
		addlisten(jButton59, 7, 2);
		addlisten(jButton60, 7, 3);
		addlisten(jButton61, 7, 4);
		addlisten(jButton62, 7, 5);
		addlisten(jButton63, 7, 6);
		addlisten(jButton64, 7, 7);
	}

}